### ISSUE TITLE
Merge in davidreynolds/gos2

### ISSUE THREAD

**Issue by adamalix** [golang/geo#1]
Is there a world in which we can merge https://github.com/davidreynolds/gos2?  It adds RegionCoverer, completes the implementation of `Region` on `Cap`, `CellUnion`, and `Rect`.  It's well tested and I am currently using it in production with no problems.

**Comment by adamalix** [comment]
cc @davidreynolds

**Comment by j16sdiz** [comment]
https://github.com/Logician/geo have some `Region` on `Cap` too. Not tested, not sure the quality.

**Comment by dsymonds** [comment]
See if 981e3e5 meets your needs.

Sorry for the long delay.

**Comment by adamalix** [comment]
Covers our needs quite nicely. Thanks!
