### ISSUE TITLE
s1/interval.go: Improper handling of floating point errors

### ISSUE THREAD

**Issue by yjh0502** [golang/geo#10]
There is a comment[1] says that epsilon `math.Nextafter(0, 1)` can handle 1-bit floating point rounding error for each endpoint, but it doesn't. `math.Nextafter(1,2)-1` does handle 1-bit rounding errors.

Here's a demo: https://play.golang.org/p/F78ciwSUoI

[1] https://github.com/golang/geo/blob/master/s1/interval.go#L293-L294

**Comment by dsymonds** [comment]
@rsned thoughts?

**Comment by dsymonds** [comment]
I think the C++ equivalent uses `DBL_EPSILON`.
