### ISSUE TITLE
Cell.Edge does not do what is claimed in doc comment

### ISSUE THREAD

**Issue by djadala** [golang/geo#11]
Cell.Edge returns edge from vertex 3 to vertex 0 if k >= 3, documentation claim:
edge from vertex k to vertex k+1 (mod 4)

switch should be `switch k%4 {` or `switch k&0x03 {`
https://github.com/golang/geo/blob/master/s2/cell.go#L78

**Comment by dsymonds** [comment]
@rsned ?

**Comment by dsymonds** [comment]
Hah, it looks like the C++ we ported from also has this mistake.

**Comment by dsymonds** [comment]
Actually, it's just a misleading comment. It isn't saying it returns `vertex k (mod 4)`, but only `vertex k+1 (mod 4)`, implicitly assuming that k is 0-3.

**Comment by dsymonds** [comment]
I'll clarify the doc comment.
