### ISSUE TITLE
Is the `.id()` equivalent in s2geometry-node equivalent to `.pos()`

### ISSUE THREAD

**Issue by Gacnt** [golang/geo#12]
I'm trying to use this package for a project over `s2geometry-node`

Which has this:
```
var origin = new s2.S2CellId(new s2.S2LatLng(lat, lng)).parent(15);
var walk = [origin.id()];
```
Which does this: https://github.com/billyriantono/s2geometry-node/blob/master/API.md#cellidid---number

I'm trying to achieve similar results by doing:
```
ll := s2.LatLngFromDegrees(location.Latitude, location.Longitude)
cid := s2.CellIDFromLatLng(ll).Parent(15)
cid.Pos()
```

**Comment by dsymonds** [comment]
Sorry, I don't know anything about that node package. Can you state exactly what you're trying to get from the `s2.CellID`?

**Comment by Gacnt** [comment]
Hi thanks for the reply. I'm not sure to be honest I'm trying to port over
something from Node to Go, there's a small part that looks like this:

```

function getNeighbors(lat, lng) {
var origin = new s2.S2CellId(new s2.S2LatLng(lat, lng)).parent(15);
var walk = [origin.id()];
// 10 before and 10 after
var next = origin.next();
var prev = origin.prev();
for (var i = 0; i < 10; i++) {
// in range(10):
walk.push(prev.id());
walk.push(next.id());
next = next.next();
prev = prev.prev();
}
return walk;
}

```

I don't know anything about s2 geo I'm just trying to recreate this very
small function but I'm getting a different result

The id() from the node package gives me a uint64 starting with the number 6

The pos() gives me a uint64 starting with the number 1

**Comment by Gacnt** [comment]
Looks like doing `uint64(cid)` gives me the numbers I'm looking for. Thanks.
