### ISSUE TITLE
Cell rect bounds != Union(cell children rect bounds)

### ISSUE THREAD

**Issue by zlanka** [golang/geo#13]
I have and cell with cellid **6ad642d0f** with rect bounds as follows
[](url)
<img width="408" alt="screen shot 2016-10-10 at 2 45 18 pm" src="https://cloud.githubusercontent.com/assets/12894078/19231576/5e0cfa44-8ef8-11e6-8e6e-203bf2db4758.png">

And its children with rect bounds as follows 
[](url)
<img width="447" alt="screen shot 2016-10-10 at 2 45 11 pm" src="https://cloud.githubusercontent.com/assets/12894078/19231580/62076990-8ef8-11e6-991c-f1a149595dde.png">

Is it a normal behaviour?

**Comment by nikolaydubina** [comment]
same. something is wrong with children

**Comment by nikolaydubina** [comment]
UPD: I got same checkboard pattern directly accessing Children().

to break down cell into children, you got to use iterators over children. check Denormalize method, this works with minLevel and set mod=1
