### ISSUE TITLE
stuv_test.go: dead test code

### ISSUE THREAD

**Issue by yjh0502** [golang/geo#21]
There's dead test code on `stuv_test.go` [1]

`siRandom` and `tiRandom` is initialized to zero, `siRandom > maxSiTi || tiRandom > maxSiTi` is always false, therefore `siRandom` and `tiRandom` will be always zero for the testcase.

Here's simple fix.
```go
siRandom = uint64(maxSiTi)
tiRansom = uint64(maxSiTi)
```

https://github.com/golang/geo/blob/d6335c766376e743cb50b2c92e981e3219f405d7/s2/stuv_test.go#L273-L278

**Comment by dsymonds** [comment]
@rsned, can you take a look and fix internally if needed?

**Comment by rsned** [comment]
Will do.
