### ISSUE TITLE
s1.ChordAngle: duplicated testcase

### ISSUE THREAD

**Issue by yjh0502** [golang/geo#23]
There is a duplicated testcase on ChordAngle. I doubt there might be a mistake while porting source code.

https://github.com/golang/geo/blob/5747e9816367bd031622778e3e538f9737814005/s1/chordangle_test.go#L43-L44

**Comment by yjh0502** [comment]
Here's another one.
https://github.com/golang/geo/blob/5747e9816367bd031622778e3e538f9737814005/s1/chordangle_test.go#L66-L68

**Comment by dsymonds** [comment]
@rsned?

**Comment by rsned** [comment]
I've sent a patch to clean up the duplicate cases.
