### ISSUE TITLE
s1.ChordAngle: testcase uses constant epsilon value instead of constant variables

### ISSUE THREAD

**Issue by yjh0502** [golang/geo#24]
I think its better using `epsilon` instead of constant literal `1e-14` .

https://github.com/golang/geo/blob/5747e9816367bd031622778e3e538f9737814005/s1/chordangle_test.go#L177

**Comment by dsymonds** [comment]
@rsned?

**Comment by rsned** [comment]
Looks like we missed that one when changing to use the constant.
