### ISSUE TITLE
Inconsistency in ContainsPoint implementation from f65fe01

### ISSUE THREAD

**Issue by cstratopoulos** [golang/geo#25]
Commit `f65fe01` added several method implementations to `s2`'s `Loop` structure, such that it now fully implements the `Region` interface. This commit also included a modification to `Loop`'s `ContainsPoint` method, splitting the implementation into cases by number of vertices in the `Loop`. This implementation change introduced situations where results returned by `ContainsPoint` and `bruteForceContainsPoint` may disagree.

The method `bruteForceContainsPoint` is equivalent to the `ContainsPoint` implementation from previous commits. In new versions, `bruteForceContainsPoint` is only invoked if the `Loop` has less than 32 vertices. I'll provide a bit more discussion about isolating the issue, and the bottom of this message contains a test case which shows that `bruteForceContainsPoint` may sometimes disagree with the new implementation of `ContainsPoint`. 

The precise issue with `ContainsPoint` appears to be a false negative. It occurs when using the `LocatePoint` method of an iterator. To recreate the error reporting, consider the following code snippet adapted from the implementation of `ContainsPoint`

    /// ^^^^ omitted code ^^^^^

	// For small loops, and during initial construction, it is faster to just
	// check all the crossing.
	const maxBruteForceVertices = 32
	if len(l.vertices) < maxBruteForceVertices || l.index == nil {
		return l.bruteForceContainsPoint(p)
	}

	// Otherwise, look up the point in the index.
	it := l.index.Iterator()
	if !it.LocatePoint(p) {
		//>>>>>>> begin added code
		if l.bruteForceContainsPoint(p) {
			// Error reporting can go here:
			// bruteForceContainsPoint would return true, but if
			// we are at this point in the function, then
			// LocatePoint would have caused a false result
		}
		//>>>>>> end of added code
		return false
	}
	return l.iteratorContainsPoint(it, p)

    /// vvv code continues below vvv

This is how I was able to isolate the issue. I added similar print/error checking statements to the line 
~~~
return l.iteratorContainsPoint(it, p)
~~~
 but I encountered no situations where this caused an error. 

As promised, here is a test case which can be added to `loop_test.go` to provide a failure. Some remarks

- The vectors look pretty lamentable; they were extracted with a crude print/panic statement inserted as suggested in the snippet above, and the error occurred at some point in the code where the points in the loop had already been normalized to unit length.
- This example was originally 41 lines long, but I commented some out to make the example smaller while allowing the test to still fail. Of course it is still very unwieldy, and it may be possible to isolate the issue to a more manageable size by (temporarily) writing a separate "contains point"-esque method for `Loop` which avoids the call to `bruteForceContainsPoint`, regardless of the loop size. 

~~~
     func TestLoopAgreesBrute(t *testing.T) {
     	failLoop := LoopFromPoints([]Point{
     		Point{r3.Vector{0.165641708683984922867438, -0.682335499717461102520133, 0.712026045990996392376360}},
     		Point{r3.Vector{0.166979327473334382414549, -0.682904418669755708393154, 0.711167673026464219887544}},
     		Point{r3.Vector{0.170033862370230215432798, -0.684512796839880532928646, 0.708894009432937788339757}},
     		Point{r3.Vector{0.173220846601894046257186, -0.686324802909040188048095, 0.706365913117550037192416}},
     		Point{r3.Vector{0.174132592687058745939410, -0.685648723780406754713113, 0.706798180347390614386427}},
     		Point{r3.Vector{0.174311093817664880534224, -0.685348749932649936589257, 0.707045071786688406056953}},
     		Point{r3.Vector{0.174788277726536822598291, -0.684972450974164481785067, 0.707291877074688768445299}},
     		Point{r3.Vector{0.175010683840933378707660, -0.684597055988098723844359, 0.707600262488615072697939}},
     		Point{r3.Vector{0.178440325586863041129604, -0.682113826909010900756414, 0.709140167628373951913545}},
     		Point{r3.Vector{0.178421498442325326960756, -0.681798846893779120215129, 0.709447743859904389474025}},
     		Point{r3.Vector{0.177363651320893683793756, -0.680666029071524625315703, 0.710799473872992471079613}},
     		Point{r3.Vector{0.178797103397320800155512, -0.679841802240863102291257, 0.711229020599288497272994}},
     		Point{r3.Vector{0.179208354282632764675753, -0.679476714451123453564207, 0.711474356722725964630172}},
     		Point{r3.Vector{0.179160846488811170695854, -0.679296586466655694103167, 0.711658301925974789980955}},
     		Point{r3.Vector{0.177754755617451076776803, -0.677801803870706653931677, 0.713433922325674485520608}},
     		Point{r3.Vector{0.177407707407642972752271, -0.677442089150445014844593, 0.713861836211913458605238}},
     		Point{r3.Vector{0.177198812539136635324510, -0.677367964597019756034513, 0.713984048401930637695045}},
     		Point{r3.Vector{0.176713912637369380265184, -0.677687776492058135957564, 0.713800721962119077979025}},
     		Point{r3.Vector{0.175562077462614568590382, -0.678115763127744464178193, 0.713678477155285651001293}},
     		Point{r3.Vector{0.174399255619088117130744, -0.678994258659042504433501, 0.713128106547179396734748}},
     		Point{r3.Vector{0.173303962271755457313915, -0.679403082290932269771133, 0.713005742217052929099452}},
     		Point{r3.Vector{0.173112863740829431291601, -0.679644400955237593109359, 0.712822154999159129928898}},
     		Point{r3.Vector{0.173070942545166334136653, -0.679975956971311856769091, 0.712516067739862535290740}},
     		Point{r3.Vector{0.172611481966008672994661, -0.680156883220664032485558, 0.712454834007777759730118}},
     		Point{r3.Vector{0.172375750124909493665726, -0.680473171917579389145203, 0.712209844827564220182126}},
     		Point{r3.Vector{0.172406271752544054676193, -0.680593659565949526957240, 0.712087317692862931117759}},
     		Point{r3.Vector{0.172036150809872556699531, -0.680879570099696906915199, 0.711903486320564882205986}},
     		Point{r3.Vector{0.170830245913837386328993, -0.680606447647954415636207, 0.712454834007777759730118}},
     		Point{r3.Vector{0.170650943370862256953657, -0.680394989174694653222275, 0.712699736377530812525549}},
     		Point{r3.Vector{0.170055147795025896062526, -0.680031099872446809229132, 0.713189280566303929198568}},
     		Point{r3.Vector{0.169624646201347706320206, -0.680074463704104847927567, 0.713250449154181564992427}},
     		Point{r3.Vector{0.168510702717778293457940, -0.679902327040342591146782, 0.713678477155285651001293}},
     		// Point{r3.Vector{0.167012134825664543269497, -0.680207855705349917485592, 0.713739602276421192250666}},
     		// Point{r3.Vector{0.166730147144508150658382, -0.680341156537279445615241, 0.713678477155285651001293}},
     		// Point{r3.Vector{0.166537056793038762414483, -0.680580777692820770852222, 0.713495069183906371890203}},
     		// Point{r3.Vector{0.166566405708508558092262, -0.680958101605218635299366, 0.713128106547179396734748}},
     		// Point{r3.Vector{0.166046269466772172807012, -0.681149171530156971599013, 0.713066927097273817182099}},
     		// Point{r3.Vector{0.165986282410054197811178, -0.681419936158346062349267, 0.712822154999159129928898}},
     		// Point{r3.Vector{0.165539070261747467416313, -0.681912696549804686618756, 0.712454834007777759730118}},
     		// Point{r3.Vector{0.165464015353066290492379, -0.682122818382738138609511, 0.712271100259466050097501}},
     		// Point{r3.Vector{0.165641708683984922867438, -0.682335499717461102520133, 0.712026045990996392376360}},
     	})
     
     	failPt := Point{r3.Vector{0.171317369856565732133546, -0.681796830037278533964695, 0.711198594864013489136312}}
     
     	if failLoop.ContainsPoint(failPt) != failLoop.bruteForceContainsPoint(failPt) {
     		t.Errorf("ContainsPoint should coincide with bruteForceContainsPoint")
     	}
     
     }
~~~

**Comment by dsymonds** [comment]
@rsned

**Comment by rsned** [comment]
I will take a look and see if I can see what's going on and why there is a
difference.
