### ISSUE TITLE
Inconsistent result using RegionCoverer over Loop

### ISSUE THREAD

**Issue by prl900** [golang/geo#29]
I've come up with some results using the CellUnion method of RegionCoverer which are unexpected to me. I've created this [gist](https://gist.github.com/prl900/17a5278129df0d58f92df663d7bbdb63) to reproduce what I'm observing.

I'm basically comparing the cells covered by a Polyline containing 3 points and a Loop which is defined using the same 3 points. Using a RegionCoverer, it identifies 3 cells for the Polyline but returns an empty list of cells in the case of the Loop.

I've done some digging and although the FastCovering call identifies the same initial candidates in both cases, Loop's IntersectsCell method results in a "Disjoint" CellRelation for each of the 4 identified candidates.

I would have expected similar cells returning for both geometries or at least a non empty slice in the case of the Loop.

**Comment by dsymonds** [comment]
The Loop code has undergone some changes recently. Can you verify that you've got the most recent version of the code?

@rsned

**Comment by prl900** [comment]
I see the same results after doing: `go get -u github.com/golang/geo/s2`

**Comment by jasonpfox** [comment]
I have seen the same results,  I tried to submit comment on the pull
request / merge of this but can't find that comment...

From what I can tell, the loop code itself looks complete; however, the
underlying ShapeIndex for a loop is never populated and remains empty due
to missing functionality in ShapeIndex.  ShapeIndex query is there but
index itself is never populated and query compares against an empty
ShapeIndex.

I was wondering if shape index updates were not included or missed.

As a workaround, I am currently getting coverer on loop.RectBound() myself.

--
Jason Fox
jpfox@alumni.rice.edu

**Comment by akhenakh** [comment]
I confirm suspicious results with the loop region from master.
I had to revert back to the community implem (which works mostly anywhere but some edge cases).

**Comment by prl900** [comment]
I think @jasonpfox is right, there seems to be missing code in the ShapeIndex implementation. I'm not sure but it seems to me that when a new Shape is added to ShapeIndex using the Add() method it should also populate its private `.cells` field with the CellIDs it covers.
