### ISSUE TITLE
Support for Polygon Contains and Intersects method

### ISSUE THREAD

**Issue by pawanrawal** [golang/geo#32]
I wanted to check if its possible to add support for [Contains/Intersects](https://github.com/golang/geo/blob/master/s2/polygon.go#L512) for Polygon. Since the library doesn't yet support those methods for Polygon/MultiPolygon we just use the outer `s2.Loop` and do Intersects/Contains using that. That is error prone because it ignores the holes in the polygon. 

If it's not very complicated then I could try porting them over from the C++ library and send over a PR?

**Comment by dsymonds** [comment]
We've got a bunch of Polygon code being actively ported, so keep an eye out for those changes to roll in. Containment and intersection should be part of that.

**Comment by halfrost** [comment]
I'm also looking forward to roll in those changes ！

**Comment by dsymonds** [comment]
There's some progress in e85324b and 757167a.

**Comment by dsymonds** [comment]
Loop.Contains is in 45e0c08.

**Comment by dsymonds** [comment]
There's a bit more progress in 5868377.

**Comment by dsymonds** [comment]
There's more in a25c8cf.

We should have the full Polygon Contains and Intersects implementation out soon too.
