### ISSUE TITLE
DEPRECATED: Use CrossingSign(a,b,c,d) == Cross instead.

### ISSUE THREAD

**Issue by djadala** [golang/geo#34]
then, why not define:
```￼
func SimpleCrossing(a, b, c, d Point) bool {
    return CrossingSign(a,b,c,d) == Cross
}
```
for backward compatibility ?

**Comment by dsymonds** [comment]
It's not an exact match for degeneracies (e.g. if the segments cross only at one of the endpoints). You're welcome to drop those lines in your own code.

**Comment by djadala** [comment]
Is it good idea to include doc comment like:
```
// deprecated SimpleCrossing function can be replaced with 
// CrossingSign(a,b,c,d) == Cross or 
// CrossingSign(a,b,c,d) != DoNotCross
```
?

**Comment by dsymonds** [comment]
That's roughly what had been in the deprecation comment for quite a while.

**Comment by djadala** [comment]
Sorry for continuing this thread,
but i can't see any deprecation comment in sources & godoc,
deprecation text is only in commit message, and it suggest replacing with only
```CrossingSign(a,b,c,d) == Cross```.

Again sorry, i will stop posting more messages.

**Comment by dsymonds** [comment]
If I visit https://github.com/golang/geo/commit/ec03579dafff0d18d92b2c87cb8a2f1bc1c5bc5a, you can see the deprecation notice in s2/edge_crossings.go on line 76 on the left hand side. It suggests using `CrossingSign(a,b,c,d) == Cross`, but that's not a perfect replacement in every situation.
