### ISSUE TITLE
cell containment discrepancy

### ISSUE THREAD

**Issue by buth** [golang/geo#37]
There isn't agreement between the `Cell`, `Loop`, and `Polygon` implementations of `ContainsCell` as required by the `Region` interface.

```go
testRegions := []s2.Region{
	cell, // s2.Cell
	s2.LoopFromCell(cell),
	s2.PolygonFromCell(cell),
}

for _, region := range testRegions {
	fmt.Println(region.ContainsCell(cell))
}

// true
// false
// false
```

I don't know whether or not this is intentional, but the discrepancy seems related to [whether or not regions can be said to contain cells with which they share an edge](https://github.com/golang/geo/blob/master/s2/polygon.go#L453-L456).

**Comment by dsymonds** [comment]
One could argue that the boundary of a region is not completely contained by that region (per the `ContainsCell` docs on the `Region` interface), so the behaviour of that method on `s2.Loop` and `s2.Polygon` is reasonable. I can see how the reflexive predicate is a special case here.

I just eyeballed the Go code in parallel with the C++ code, and they look equivalent, so I might guess that the C++ code has the same behaviour. If that's the case (care to check?), then we won't change Go unless C++ changes first (consider Go to be a downstream port of the C++).

@jmr might have thoughts.

**Comment by jmr** [comment]
The same thing happens in C++, at least for the cell id I picked.

I think the comment on the [C++ S2Loop(S2Cell) constructor](https://github.com/google/s2geometry/blob/a2efd83f743f5a8d2a8b4ef1663c5703cf6735a2/src/s2/s2loop.h#L127) explains what's going on for the loop and polygon.

```c++
  // Construct a loop corresponding to the given cell.
  //
  // Note that the loop and cell *do not* contain exactly the same set of
  // points, because S2Loop and S2Cell have slightly different definitions of
  // point containment.  For example, an S2Cell vertex is contained by all
  // four neighboring S2Cells, but it is contained by exactly one of four
  // S2Loops constructed from those cells.  As another example, the S2Cell
  // coverings of "cell" and "S2Loop(cell)" will be different, because the
  // loop contains points on its boundary that actually belong to other cells
  // (i.e., the covering will include a layer of neighboring cells).
  explicit S2Loop(const S2Cell& cell);
```

The [class level loop comments](https://github.com/google/s2geometry/blob/a2efd83f743f5a8d2a8b4ef1663c5703cf6735a2/src/s2/s2loop.h#L76) explain why.
```c++
// Point containment of loops is defined such that if the sphere is subdivided
// into faces (loops), every point is contained by exactly one face.  This
// implies that loops do not necessarily contain their vertices.
//
// Note: The reason that duplicate vertices and intersecting edges are not
// allowed is that they make it harder to define and implement loop
// relationships, e.g. whether one loop contains another.  If your data does
// not satisfy these restrictions, you can use S2Builder to normalize it.
```

What documentation of `Region` says the calls should all return the same result?

@ericveach may have more to add.

**Comment by buth** [comment]
My understanding was ("this isn't a port of port of the C++ code")[https://github.com/golang/geo/pull/31#issuecomment-325535517].

**Comment by ericveach** [comment]
Jesse's explanation is correct.  And yes, there is no requirement that the Region::ContainsCell() should return the same result for "cell" and S2.LoopFromCell(cell), because those two regions are not the same.

**Comment by dsymonds** [comment]
Thanks guys. It sounds like this is working as intended, just slightly non-obvious.
