### ISSUE TITLE
Status and what's missing.

### ISSUE THREAD

**Issue by giulioungaretti** [golang/geo#4]
Hej Devs, 
  I am wondering what are the plans for this repo.

I'd be more than willing to collaborate and bring it up (feature wise to the c++ lib), but I'd love some guidance :D

**Comment by giulioungaretti** [comment]
Especially I'd love to start (selfishly) from the loop.go part. As I'd really love to make it implement the region interface.  
Should I peak at the c++ implementation and "translate" it to go ? Is this the way the rest of the lib was written ?

In case it was clear before. much  <3 <3 for the work already done

**Comment by dsymonds** [comment]
It's growing organically in fits and starts. It requires some careful review, so a pull request unfortunately isn't a very useful source of that growth.

**Comment by giulioungaretti** [comment]
@dsymonds  sweet to know. Keep up the good work, and if any kind of help is needed just ping.
