### ISSUE TITLE
CellUnion.Intersects gives incorrect results

### ISSUE THREAD

**Issue by reltuk** [golang/geo#46]
Currently, ```CellUnion.Intersects``` is implemented in terms of ```CellUnion.ContainsCellID```. It should be implemented in terms of ```CellUnion.IntersectsCellID```, as it is in the C++ library. With the current implementation, the method gives wrong results.

**Comment by dsymonds** [comment]
Thanks for the report. I'll look into it early next week.

**Comment by reltuk** [comment]
Thanks for the quick turn around here. Awesome!
