### ISSUE TITLE
Unable to understand tolerance in func (*Polyline) SubsampleVertices

### ISSUE THREAD

**Issue by jackielii** [golang/geo#48]
In the test file https://github.com/golang/geo/blob/master/s2/polyline_test.go#L152, it defines the polyline like shown in the image:

![screenshot_2019-03-07_01-10-15](https://user-images.githubusercontent.com/360983/53924988-30c44b00-4076-11e9-950b-ff6e8e879f38.png)

coordinates are: `"0:0, 0:1, -1:2, 0:3, 0:4, 1:4, 2:4.5, 3:4, 3.5:4, 4:4"`
Even with tolerance 3 degrees, we get only the first and last:
```
		{
			have:      polyStr,
			tolerance: 3.0,
			want:      []int{0, 9},
		},
```
In my understanding the angles are way bigger than 5 degrees?

**Comment by dsymonds** [comment]
The angles described here are the spherical angles between the vectors extending from the centre of the imaginary S2 sphere, not the surface angles. Compare with s2.Point.Distance and similar.

**Comment by jackielii** [comment]
Thanks!
