### ISSUE TITLE
Polygon and RegionCoverer not working

### ISSUE THREAD

**Issue by arigon** [golang/geo#49]
Hello

I created a polygon/triangle by using LoopFromPoints() and PolygonFromLoops() with 1 loop and tried to get the cells by using RegionCoverer() and SimpleRegionCovering(). Unfortunately it isn't working, the result: 6.3 Mio. level 13 cells. Expected result: 2

It works fine by using 3 polylines though.

The check polygon.ContainsPoint() fails as well for a given point, which should be inside the polygon.

It seems the problem is similar to #29. 

I'm using go1.11 on MacOS 10.14.3.

Regards
Alex

**Comment by rsned** [comment]
Do you have example code of the triangle you are creating that doesn't work?

**Comment by rsned** [comment]
Getting millions instead of two sounds a lot like the triangle may be being defined inside out of how you want (CW vs CCW). e.g, you are enclosing most of the globe instead of just the small triangle.

**Comment by arigon** [comment]
I thought I already tried changing the points to CCW.. now I changed the order into CCW and it works. Thanks for the help!

Is there a way to define, if CW or CCW should be used?

**Comment by dsymonds** [comment]
The APIs generally document their assumption about the order of the points. If you want control over that, simply reverse the points on your end first; there isn't a way for this library to know whether you want a small area, or the inverse area.
