### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by djadala** [golang/geo#5]
Hi,

just realized that LatLngFromDegrees does not convert argumens:

```go
package main
import (
	"fmt"
	"github.com/golang/geo/s2"
	"github.com/golang/geo/s1"
)

func main() {
    fmt.Println(  s1.Degree, float64(s1.Degree), s2.LatLngFromDegrees(1, 1))  
}
```
result:
```
1.0000000 0.017453292519943295 [1.0000000, 1.0000000]

go version
go version go1.6 linux/amd64

```

go compiled from source

**Comment by rsned** [comment]
LatLng prints out the Lat and Lng as s1.Angles, and s1.Angle's String
method formats the numbers as degrees, so that's why you are seeing the
last value as [1.00000, 1.00000]

- Robert

**Comment by djadala** [comment]
Ah, sorry for noise, got it
Thanks.
