### ISSUE TITLE
Polygon Intetersection didn't work for triangle and rectangle

### ISSUE THREAD

**Issue by outsidebedisdoor** [golang/geo#50]
So I use S2.Polygon Intersects methods. 

My points as a triangle and another rectangle (when drawing) have no intersection. However, the intersect methods will return true.

I put all the points inside of s2.Point and construct loop using list of s2.point and construct polygon using list of loop. Could some one tell me if I use them wrong or if the algorithm has some problems.

**Comment by rsned** [comment]
Can you paste an example of the code you are using to construct the two
shapes?

**Comment by outsidebedisdoor** [comment]
NVM I found out that I have to read the point using 

s2.PointFromLatLng(s2.LatLng{s1.Angle(PointLatitude), s1.Angle(PointLongitude)})

and then it works. Thanks
