### ISSUE TITLE
Polyline intersection

### ISSUE THREAD

**Issue by sunnypatel165** [golang/geo#52]
As already highlighted in #44 - there are quite a few C++ boolean functions missing from this port. e.g. one that I was looking at right now was Polyline intersecting another Polyline(and others soon)

I see the following:

```
// TODO(roberts): Differences from C++.
// Suffix
// Interpolate/UnInterpolate
// Intersects(Polyline) --> One I am interested in 
```

Do we have a list of all remaining tasks? Is anyone actively working on them? Or, is there any rough timeline of when we plan to add these features? :)

**Comment by dsymonds** [comment]
I think most files that correspond to equivalent C++ files have a TODO list like that, but the top-level README lists the parity relative to C++. Some are being worked on. There isn't a timeline.

**Comment by dsymonds** [comment]
See 93f1d80, which adds `Polyline.Intersects`.
