### ISSUE TITLE
[question] distance between points

### ISSUE THREAD

**Issue by Edwin-Luijten** [golang/geo#56]
I'm loving the library, really well put together!

I'd like to find the distance in meters between two points.

What did I try:
```
a: = s2.PointFromLatLng()
b: = s2.PointFromLatLng()
distance := a.Distance(b) // <- how do i convert this to mm/m/km
```
Not even sure if I'm using the correct methods.

**Comment by Edwin-Luijten** [comment]
That function is indeed i need to use (in reverse ofc). Thanks =).

**Comment by idc77** [comment]
What is `a`?

I'm not a mathematician. Can you give a full example on how to calculate the distance between 2 points?
