### ISSUE TITLE
Polygon .Invert followed by .ContainsPoint panic

### ISSUE THREAD

**Issue by jamespwilliams** [golang/geo#68]
Calling `.Invert` on a polygon and then calling `.ContainsPoint` causes a panic (at least, when initiated using `PolygonFromLoops` with a list of loops containing a single `RegularLoop`, I haven't tested other ways of initiating polygons).

https://play.golang.org/p/5rVu_MkN9vN

**Comment by dsymonds** [comment]
I imagine this could quite likely be the same bug as #69.
