### ISSUE TITLE
Inverted Loops don't contain expected Points

### ISSUE THREAD

**Issue by jamespwilliams** [golang/geo#69]
This issue might just be me not understanding the semantics of this library's `Loop.Invert` function, but my expectation is that a Loop which doesn't contain a Point `p` should then contain `p` when it is `.Invert`'ed. This is not currently the case in this library. 

I've put together a small playground demonstrating this behaviour below:

https://play.golang.org/p/1touvyS49sE

**Comment by jamespwilliams** [comment]
Interestingly this does work when the number of vertices is reduced to 10. It appears to stop working at 32 vertices.

https://play.golang.org/p/JbpsZGYrRK4

**Comment by rsned** [comment]
32 is the split point between brute force and index when using ContainsPoint, so thats a pretty good guess as to where it's going wrong.

https://github.com/golang/geo/blob/master/s2/polygon.go#L593

I will do some debugging to see if I can see whats wrong.
