### ISSUE TITLE
Get a random point from a shape

### ISSUE THREAD

**Issue by Edwin-Luijten** [golang/geo#92]
Hello,

I'd like to get a random point from a geo shape. And I'm trying to figure out if it's possible with this library.
Given I have these coordinates, this represents a square starting from the bottom left, but could be a more complex shape:
```json
[
        {
          "latitude": 52.3793442,
          "longitude": 4.8989278
        },
        {
          "latitude": 52.3794194,
          "longitude": 4.8988457
        },
        {
          "latitude": 52.3795301,
          "longitude": 4.899796
        },
        {
          "latitude": 52.3791095,
          "longitude": 4.8993511
        }
      ]
```
How would I go about to get a random point from within this shape?

**Comment by rsned** [comment]
For a rectangular shape like that, if you look in the test code there are some methods that draw random sample points such as 
 samplePointFromRect (https://github.com/golang/geo/blob/master/s2/s2_test.go#L265 ) that you could model after. They are for tests, so there is no specific guarantee of performance or true randomness, but they work good enough for our tests.

For other shapes we do have some test methods that do other samples.

s2_test.go: samplePointFromCap
edge_query_test.go:sampleBoundaryFromCap(
edge_query_test.go:func sampleEdgeFromIndex(
edge_query_test.go:func sampleCellFromIndex(

**Comment by Edwin-Luijten** [comment]
Oh, awesome =D, this will help me to build what I wan't, will comment back with the code once done.
Did not clarified it in the question I think but my goal is to have a shape (2D building floor), and pick a random point that's within the shape. 

Based on this i'll show an avatar on a map to add some gamifcation, like chasing a bunny or whatever.
